### ISSUE TITLE
Исходники

### ISSUE THREAD

**Issue by imKota** [dsp2003/ae#1]
Здравствуйте @dsp2003 

Скажите пожалуйста, где можно скачать сорсы последнего билда?

**Comment by dsp2003** [comment]
Re: [dsp2003/ae] Исходники (#1)


http://wks.arai-kibou.ru/ae.php?p=dl

You can also find the unfinished Delphi XE port sources there. We couldn't finish the port due to problems with JCL/JVCL libraries compilation.

**Comment by imKota** [comment]
@dsp2003 thanks!
