### ISSUE TITLE
add support to SinglusEngine

### ISSUE THREAD

**Issue by marcussacana** [dsp2003/ae#11]
its possible add support to extract/repack the Angel Beats scripts files and images (g00)? if possible wait the full version relase.... it's a very good game... (i know kkkkkkk)

**Comment by dsp2003** [comment]
Currently very hard to implement, because the image converter's engine needs entire rewrite, plus the g00 has tons of metadata, and while technically it's possible to export it via .ini files, it's hard to implement its compression.

**Comment by marcussacana** [comment]
and only extract/repack?

**Comment by dsp2003** [comment]
The image decoder works in a different way from the archiver. It can load and save (meta)data on-the-fly. The problem is its code was written by me about 8 years ago, when I had no idea about proper code patterns, and adding the new format is like adding a new hand on the forehead. /)_<

**Comment by MeruP** [comment]
adding support for siglus engine is not really useful since even if archive format is similar between the games, encryption keys are not and without some debugging voodoo, whatever you extract from the archives will be useless.

**Comment by dsp2003** [comment]
MeruP, thanks. I had no idea Key began the same infamous practice with archive encryption as minori.

**Comment by marcussacana** [comment]
wow, and the minori, you know tool for the eden* (steam version) with repack?
