### ISSUE TITLE
UniPlug\UniPlug.pas ?

### ISSUE THREAD

**Issue by imKota** [dsp2003/ae#20]
Hello!
Could you share the source code of "UniPlug"?

**Comment by dsp2003** [comment]
Umm... This is the first time I ever heard of it.

**Comment by imKota** [comment]
@dsp2003 https://github.com/dsp2003/ae/blob/ac3ad028474760922e2a4a6cb6841a048ab7ec11/src/lib/_jiskit/Unicode%20dialogs/Unicode_Dialogs_Demo.dsk#L5

**Comment by dsp2003** [comment]
Ah, that's from JISKit demo program. It was written by Proger_XP, which I no longer have contact with. :(

To be honest, I never tried to compile nor looked at his demos.
